# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: currency-ingress
#   annotations:
#     nginx.ingress.kubernetes.io/rewrite-target: /
# spec:
#   ingress.
#   rules:
#   - http:
#       paths:
#       - path: /currency-exchange/*
#         backend:
#           serviceName: currency-exchange
#           servicePort: 8000          
#       - path: /currency-conversion/*
#         backend:
#           serviceName: currency-conversion
#           servicePort: 8100